Repository TeamBookTez/nextjs-book-stairs, pull requests merged in 2022-07, with the labels that each got.

#47 [AddBook] 책추가 페이지 옮기기
  components/bookNote/ExitModal.tsx
  components/bookNote/drawer/DrawerHeader.tsx
  components/bookNote/preNote/PreNotePostSection.tsx
  components/bookcase/addBook/AddBookDefault.tsx
  components/bookcase/addBook/AlertToast.tsx
  components/bookcase/addBook/BookEmpty.tsx
  components/bookcase/addBook/BookInfoWrapper.tsx
  components/bookcase/addBook/BookList.tsx
  components/bookcase/addBook/ModalWrapper.tsx
  components/bookcase/addBook/SearchBar.tsx
  components/bookcase/addBook/ShowModal.tsx
  components/bookcase/addBook/StickyHeader.tsx
  components/bookcase/cardSection/AddBookCard.tsx
  components/bookcase/cardSection/BookCard.tsx
  components/bookcase/cardSection/Empty.tsx
  components/bookcase/index.ts
  components/common/Empty.tsx
  components/common/Loading.tsx
  components/common/styled/Img.tsx
  components/common/styled/NoteModalWrapper.tsx
  components/landing/LandingExperiment.tsx
  components/landing/LandingInfo.tsx
  components/landing/LandingSuggestion.tsx
  components/landing/LandingValidation.tsx
  components/login/LoginNavSection.tsx
  components/main/Banner.tsx
  components/myPage/TopBanner.tsx
  core/api.ts
  pages/bookcase/add-book.tsx
  pages/bookcase/index.tsx
  pages/to-be.tsx
  public/assets/icons/index.ts
  public/assets/icons/toastAlertIcon.svg
  util/escape.ts
  util/hooks/useDebounce.ts
Labels: :tada: feature, 🐜소령

#49 Feature add book
  components/bookNote/BookNoteHeader.tsx
  components/bookNote/preNote/PreNote.tsx
  components/bookcase/Cards.tsx
  components/main/Banner.tsx
  components/signup/LastStep.tsx
  package.json
  yarn.lock
Labels: :hammer_and_wrench: fix, 🐜소령

#51 Release/1.0.0
  components/bookNote/ExitModal.tsx
  components/bookNote/Navigation.tsx
  components/bookNote/SavePoint.tsx
  components/bookNote/periNote/ChildQANode.tsx
  components/bookNote/periNote/PeriNote.tsx
  components/bookNote/periNote/TopAnswerContainer.tsx
  components/bookNote/preNote/PreNote.tsx
  components/bookcase/addBook/BookList.tsx
  components/bookcase/addBook/ShowModal.tsx
  components/bookcase/cardSection/BookCard.tsx
  components/common/PopUpDelete.tsx
  components/landing/MobileLandingMotivation.tsx
  components/landing/index.ts
  components/main/RecentBooks.tsx
  components/myPage/ServiceContent.tsx
  components/myPage/TopBanner.tsx
  components/myPage/UserContent.tsx
  core/atom.ts
  core/axios.ts
  pages/book-note/[reviewId]/index.tsx
  pages/bookcase/add-book.tsx
  pages/index.tsx
  pages/my-page.tsx
  types/bookcase.ts
  util/hooks/useFetchBookNote.tsx
  util/hooks/useUser.tsx
  util/hooks/useUserInfo.ts
  util/hooks/useUserInfo.tsx
Labels: :construction: refactor, :hammer_and_wrench: fix, :tada: feature, 🐜소령

#53 Feature fix example kkm
  next.config.js
  package.json
  public/assets/asset.d.ts
  yarn.lock
Labels: :hammer_and_wrench: fix, 🦅규민

#54 [Feature] perinote hooks kkm
  components/bookNote/periNote/ChildQANode.tsx
  components/bookNote/periNote/PeriNote.tsx
  package.json
  types/landing.ts
  util/hooks/useMediaQuery.tsx
  util/hooks/useUpdatePeriNote.tsx
  yarn.lock
Labels: :tada: feature, 🦅규민
