Repository TeamBookTez/nextjs-book-stairs, pull requests merged in 2022-06, with the labels that each got.

#31 [Common] refactoring theme fonts
  pages/_app.tsx
  styles/Home.module.css
  styles/emotion.d.ts
  styles/globals.css
  styles/theme.ts
Labels: :construction: refactor, 🐶주함

#35 [BookNote] 북노트 마이그레이션 1
  .eslintrc.json
  components/bookNote/Navigation.tsx
  components/bookNote/SavePoint.tsx
  components/bookNote/index.ts
  components/bookNote/periNote/PeriNote.tsx
  components/bookNote/periNote/index.ts
  components/bookNote/preNote/PreNote.tsx
  components/bookNote/preNote/PreNoteFormContainer.tsx
  components/bookNote/preNote/PreNotePostSection.tsx
  components/bookNote/preNote/PreNoteThirdArticle.tsx
  components/bookNote/preNote/index.ts
  components/bookNote/stepUp/StepUpContentWrapper.tsx
  components/bookcase/addBook/ShowModal.tsx
  components/bookcase/cardSection/BookCard.tsx
  components/common/AlertLabel.tsx
  components/common/PopUpDelete.tsx
  components/common/styled/Input.tsx
  components/layout/MainLayout.tsx
  components/login/LoginForm.tsx
  components/login/LoginNavSection.tsx
  components/login/PwdSightIcon.tsx
  components/login/index.ts
  components/main/MainHeader.tsx
  components/myPage/ServiceContent.tsx
  components/myPage/TopBanner.tsx
  components/myPage/UserContent.tsx
  components/myPage/WithdrawContentConfirm.tsx
  core/api.ts
  core/atom.ts
  core/axios.ts
  next.config.js
  package.json
  pages/_document.tsx
  pages/book-note/[reviewId]/detail-book-note.tsx
  pages/book-note/[reviewId]/detail.tsx
  pages/book-note/[reviewId]/index.tsx
  pages/book-note/detail-example.tsx
  pages/book-note/example.tsx
  pages/bookcase/add-book.tsx
  pages/bookcase/index.tsx
  pages/index.tsx
  pages/login.tsx
  pages/main.tsx
  pages/my-page.tsx
  pages/to-be.tsx
  types/bookNote.ts
  types/index.ts
  types/login.ts
  util/check.ts
  util/clearLocalStorage.ts
  util/hooks/useCheckLoginState.tsx
  util/hooks/useFetchBookNote.tsx
  util/hooks/useToast.tsx
  util/hooks/useUser.ts
  util/hooks/useUserInfo.ts
  util/referralLinkList.ts
  yarn.lock
Labels: :construction: refactor, :tada: feature, 🐶주함

#36 [Login] 로그인 폼 & axios 세팅 교체
  components/login/LoginForm.tsx
  components/main/RecentBooks.tsx
  components/myPage/UserContent.tsx
  components/myPage/WithdrawContentConfirm.tsx
  core/api.ts
  core/axios.ts
  core/localStorage.ts
  types/index.ts
  util/clearLocalStorage.ts
  util/hooks/useUser.ts
  util/hooks/useUserInfo.ts
Labels: :construction: refactor, :tada: feature, 🐜소령

#37 [BookNote] 북노트 마이그레이션 2
  components/bookNote/ExitModal.tsx
  components/bookNote/Navigation.tsx
  components/bookNote/periNote/ChildQANode.tsx
  components/bookNote/periNote/Complete.tsx
  components/bookNote/periNote/HeaderLabel.tsx
  components/bookNote/periNote/PeriNote.tsx
  components/bookNote/periNote/PeriNotePostSection.tsx
  components/bookNote/periNote/TopAnswerContainer.tsx
  components/bookNote/periNote/TopQuestionContainer.tsx
  components/bookNote/periNote/index.ts
  components/bookNote/preNote/InputQuestion.tsx
  components/bookNote/preNote/PreNote.tsx
  components/bookNote/preNote/PreNotePostSection.tsx
  components/bookNote/preNote/PreNoteThirdArticle.tsx
  components/common/styled/Icon.tsx
  components/common/styled/MenuWrapper.tsx
  components/main/Banner.tsx
  core/api.ts
  core/bookNote/childNodeLabelColor.ts
  package.json
  pages/book-note/[reviewId]/index.tsx
  types/bookNote.ts
  util/bookNoteTree.ts
  util/hooks/useFetchBookNote.tsx
  util/hooks/useUser.ts
  util/tree.ts
  yarn.lock
Labels: :construction: refactor, :tada: feature, 🐶주함

#46 Feature signup
  components/bookNote/preNote/PreNote.tsx
  components/common/AlertLabel.tsx
  components/common/styled/Signup.tsx
  components/login/LoginForm.tsx
  components/login/PwdSightIcon.tsx
  components/signup/FirstStep.tsx
  components/signup/LastStep.tsx
  components/signup/PasswordInput.tsx
  components/signup/SecondStep.tsx
  components/signup/SignupForm.tsx
  components/signup/ThirdStep.tsx
  components/signup/index.ts
  core/api.ts
  core/axios.ts
  next.config.js
  pages/login.tsx
  pages/signup/index.tsx
  pages/signup/welcome.tsx
  public/assets/icons/index.ts
  public/assets/icons/signupCheckingIcon.svg
  types/signup.ts
Labels: :tada: feature, 🐜소령
